// export const INTOLERANCES = [
//   'Dairy',
//   'Egg',
//   'Gluten',
//   'Grain',
//   'Peanut',
//   'Seafood',
//   'Sesame',
//   'Shellfish',
//   'Soy',
//   'Sulfite',
//   'Tree Nut',
//   'Wheat']


// export const CUISINES = [
//   'African',
//   'American',
//   'British',
//   'Cajun',
//   'Caribbean',
//   'Chinese',
//   'Eastern European',
//   'European',
//   'French',
//   'German',
//   'Greek',
//   'Indian',
//   'Irish',
//   'Italian',
//   'Japanese',
//   'Jewish',
//   'Korean',
//   'Latin American',
//   'Mediterranean',
//   'Mexican',
//   'Middle Eastern',
//   'Nordic',
//   'Southern',
//   'Spanish',
//   'Thai',
//   'Vietnamese',
// ]

export const INTOLERANCES = [
  { value: 'dairy', label: 'Dairy' },
  { value: 'egg', label: 'Egg' },
  { value: 'gluten', label: 'Gluten' },
  { value: 'grain', label: 'Grain' },
  { value: 'peanut', label: 'Peanut' },
  { value: 'seafood', label: 'Seafood' },
  { value: 'sesame', label: 'Sesame' },
  { value: 'shellfish', label: 'Shellfish' },
  { value: 'soy', label: 'Soy' },
  { value: 'sulfate', label: 'Sulfite' },
  { value: 'tree nut', label: 'Tree Nut' },
  { value: 'wheat', label: 'Wheat' }]


export const CUISINES = [
  { value: 'african', label: 'African' },
  { value: 'american', label: 'American' },
  { value: 'british', label: 'British' },
  { value: 'cajun', label: 'Cajun' },
  { value: 'caribbean', label: 'Caribbean' },
  { value: 'chinese', label: 'Chinese' },
  { value: 'eastern european', label: 'Eastern European' },
  { value: 'european', label: 'European' },
  { value: 'french', label: 'French' },
  { value: 'german', label: 'German' },
  { value: 'greek', label: 'Greek' },
  { value: 'indian', label: 'Indian' },
  { value: 'irish', label: 'Irish' },
  { value: 'italian', label: 'Italian' },
  { value: 'japanese', label: 'Japanese' },
  { value: 'jewish', label: 'Jewish' },
  { value: 'korean', label: 'Korean' },
  { value: 'latin american', label: 'Latin American' },
  { value: 'mediterranean', label: 'Mediterranean' },
  { value: 'mexican', label: 'Mexican' },
  { value: 'middle easter', label: 'Middle Eastern' },
  { value: 'nordic', label: 'Nordic' },
  { value: 'southern', label: 'Southern' },
  { value: 'spanish', label: 'Spanish' },
  { value: 'thai', label: 'Thai' },
  { value: 'vietnamese', label: 'Vietnamese' },
]